# 使用的模型路径
model_path = 'models/best.pt'
names = {0: 'Chihuahua', 1: 'Japanese_spaniel', 2: 'Maltese_dog', 3: 'Pekinese', 4: 'Shih-Tzu', 5: 'Blenheim_spaniel', 6: 'papillon', 7: 'toy_terrier', 8: 'Rhodesian_ridgeback', 9: 'Afghan_hound', 10: 'basset',
         11: 'beagle', 12: 'bloodhound', 13: 'bluetick', 14: 'black-and-tan_coonhound', 15: 'Walker_hound', 16: 'English_foxhound', 17: 'redbone', 18: 'borzoi', 19: 'Irish_wolfhound', 20: 'Italian_greyhound',
         21: 'whippet', 22: 'Ibizan_hound', 23: 'Norwegian_elkhound', 24: 'otterhound', 25: 'Saluki', 26: 'Scottish_deerhound', 27: 'Weimaraner', 28: 'Staffordshire_bullterrier', 29: 'American_Staffordshire_terrier', 30: 'Bedlington_terrier',
         31: 'Border_terrier', 32: 'Kerry_blue_terrier', 33: 'Irish_terrier', 34: 'Norfolk_terrier', 35: 'Norwich_terrier', 36: 'Yorkshire_terrier', 37: 'wire-haired_fox_terrier', 38: 'Lakeland_terrier', 39: 'Sealyham_terrier', 40: 'Airedale',
         41: 'cairn', 42: 'Australian_terrier', 43: 'Dandie_Dinmont', 44: 'Boston_bull', 45: 'miniature_schnauzer', 46: 'giant_schnauzer', 47: 'standard_schnauzer', 48: 'Scotch_terrier', 49: 'Tibetan_terrier', 50: 'silky_terrier',
         51: 'soft-coated_wheaten_terrier', 52: 'West_Highland_white_terrier', 53: 'Lhasa', 54: 'flat-coated_retriever', 55: 'curly-coated_retriever', 56: 'golden_retriever', 57: 'Labrador_retriever', 58: 'Chesapeake_Bay_retriever', 59: 'German_short-haired_pointer', 60: 'vizsla',
         61: 'English_setter', 62: 'Irish_setter', 63: 'Gordon_setter', 64: 'Brittany_spaniel', 65: 'clumber', 66: 'English_springer', 67: 'Welsh_springer_spaniel', 68: 'cocker_spaniel', 69: 'Sussex_spaniel', 70: 'Irish_water_spaniel',
         71: 'kuvasz', 72: 'schipperke', 73: 'groenendael', 74: 'malinois', 75: 'briard', 76: 'kelpie', 77: 'komondor', 78: 'Old_English_sheepdog', 79: 'Shetland_sheepdog', 80: 'collie',
         81: 'Border_collie', 82: 'Bouvier_des_Flandres', 83: 'Rottweiler', 84: 'German_shepherd', 85: 'Doberman', 86: 'miniature_pinscher', 87: 'Greater_Swiss_Mountain_dog', 88: 'Bernese_mountain_dog', 89: 'Appenzeller', 90: 'EntleBucher',
         91: 'boxer', 92: 'bull_mastiff', 93: 'Tibetan_mastiff', 94: 'French_bulldog', 95: 'Great_Dane', 96: 'Saint_Bernard', 97: 'Eskimo_dog', 98: 'malamute', 99: 'Siberian_husky', 100: 'affenpinscher',
         101: 'basenji', 102: 'pug', 103: 'Leonberg', 104: 'Newfoundland', 105: 'Great_Pyrenees', 106: 'Samoyed', 107: 'Pomeranian', 108: 'chow', 109: 'keeshond', 110: 'Brabancon_griffon',
         111: 'Pembroke', 112: 'Cardigan', 113: 'toy_poodle', 114: 'miniature_poodle', 115: 'standard_poodle', 116: 'Mexican_hairless', 117: 'dingo', 118: 'dhole', 119: 'African_hunting_dog'}


CH_names = ['吉娃娃', '日本宫廷犬', '马耳他犬', '北京犬', '西施犬', '查理王小猎犬', '蝴蝶犬', '玩具梗', '罗得西亚背脊犬', '阿富汗猎犬', '巴吉度猎犬', '比格犬', '血猎犬', '布鲁提克犬', '黑棕猎浣熊犬', '树猎犬', '英国猎狐犬', '红骨猎犬', '俄罗斯猎狼犬', '爱尔兰狼犬', '意大利灰狗', '小猎犬', '伊比赞猎犬', '挪威猎麋犬', '水獭猎犬', '萨路基犬', '苏格兰猎鹿犬', '威玛猎犬', '斯塔福郡斗牛梗', '美国斯塔福郡梗', '贝灵顿梗', '边境梗', '凯利蓝梗', '爱尔兰梗', '诺福克梗', '诺里奇梗', '约克夏梗', '刚毛狐梗', '湖畔梗', '锡利哈姆梗', '艾尔代尔梗', '凯恩梗', '澳洲梗', '丹迪丁蒙梗', '波士顿梗', '迷你雪纳瑞', '巨型雪纳瑞', '标准雪纳瑞', '苏格兰梗', '西藏梗', '丝毛梗', '软毛麦色梗', '西高地白梗', '拉萨犬', '平毛寻回犬', '卷毛寻回犬', '金毛寻回犬', '拉布拉多寻回犬', '切萨皮克湾寻回犬', '德国短毛指示犬', '匈牙利维兹拉犬', '英国塞特犬', '爱尔兰塞特犬', '戈登塞特犬', '布列塔尼犬', '克伦伯犬', '英国史宾格犬', '威尔士史宾格犬', '可卡犬', '萨塞克斯犬', '爱尔兰水猎犬', '匈牙利古瓦斯犬', '梗犬', '比利时格罗宁达尔犬', '比利时马里努犬', '布里亚德犬', '澳洲牧羊犬', '匈牙利柯蒙犬', '古代英国牧羊犬', '喜乐蒂牧羊犬', '边境牧羊犬', '边境牧羊犬', '佛兰德牧羊犬', '罗得维尔犬', '德国牧羊犬', '杜宾犬', '迷你杜宾', '大瑞士山地犬', '伯恩山犬', '阿彭策尔山地犬', '恩特尔布赫山犬', '拳师犬', '英国斗牛犬', '藏獒', '法国斗牛犬', '大丹犬', '圣伯纳犬', '美洲爱斯基摩犬', '阿拉斯加雪橇犬', '西伯利亚雪橇犬', '猴脸梗', '巴辛吉犬', '巴哥犬', '莱昂贝格犬', '纽芬兰犬', '大白熊犬', '萨摩耶犬', '博美犬', '松狮犬', '荷兰毛狮犬', '布鲁塞尔格力芬犬', '彭布罗克威尔士柯基犬', '卡迪根威尔士柯基犬', '玩具贵宾', '迷你贵宾', '标准贵宾', '墨西哥无毛犬', '澳洲野狗', '亚洲野狗', '非洲狩猎犬']